### PR TITLE
support 0.0.3 breaking change to postcss opts

### PR DESCRIPTION
**Pull request by kylemac**
feel free to tack on the `sugarss` here too. i just wasn't sure how it'd effect the `root/assets/css` files, and if they'd need to be `.sss`

### CODE REVIEW

**Comment by jenius** [comment]
Updated with some new better deps. If this looks good to you, merge up @kylemac ?

**Comment by kylemac** [comment]
@jenius looks like this doesn't fully work. first issue was that the module switched to being called `postcss-cssnext` somewhere along the way. i've added that change.

the next issue looks to be with the postcss loader (possibly something we need to fix in `roots-mini`

```sh
Error: ModuleBuildError: Module build failed: AssertionError: path must be a string
```

**Comment by jenius** [comment]
Haha I guess actually testing it would have been a good plan -- thanks. Will take a look at that piece now.

**Comment by kylemac** [comment]
@jenius can you also add a quick test that uses `roots.compile` too just to make sure the compile runs through on the generated project

**Comment by jenius** [comment]
yeah good idea, i'll work on that today

**Comment by jenius** [comment]
Weird npm error on node 4, can't load modules correctly. Merging anyway, upgrade your node.

**Pull request merged**
